name: sistema-ponto-backend
services:
  postgres:
    image: postgres:17
    container_name: postgres_sistemaponto
    environment:
      POSTGRES_USER: bruno_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sistemaponto
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    image: sistema-ponto-backend:latest
    container_name: sistema_ponto_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sistemaponto
      SPRING_DATASOURCE_USERNAME: bruno_user
      SPRING_DATASOURCE_PASSWORD: 1234
volumes:
  pgdata:
    external: true
    name: sistemaponto_pgdata
