spring.application.name=SistemaPonto

spring.jpa.open-in-view=false

# Configuração PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sistemaponto
spring.datasource.username=bruno_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# CORS
cors.allowed-origins=http://localhost:5173
